repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.4
    hooks:
      - id: go-fmt
      - id: go-lint
      - id: golangci-lint
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude: ".md"
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: test
        name: Go test
        description: Run unit and integration tests
        language: system
        entry: make test
